const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';
const SET_WALLET_AMOUNT = 'SET_WALLET_AMOUNT';
const UPDATE_WALLET_AMOUNT = 'UPDATE_WALLET_AMOUNT';
const SET_LIVE_PRICE = 'SET_LIVE_PRICE';

export {
  SET_WALLET_ADDRESS,
  SET_WALLET_AMOUNT,
  UPDATE_WALLET_AMOUNT,
  SET_LIVE_PRICE,
};
