const SET_EXPLORE_ITEMS = 'SET_EXPLORE_ITEMS';
const UPDATE_EXPLORE_ITEMS = 'UPDATE_EXPLORE_ITEMS';
const SET_AUCTION = 'SET_AUCTION';
const SET_RECENT_AUCTION = 'SET_RECENT_AUCTION';
const SET_LIVE_AUCTION = 'SET_LIVE_AUCTION';
const SET_MOST_VIEWED_AUCTION = 'SET_MOST_VIEWED_AUCTION';
const SET_HOT_BIDS_AUCTION = 'SET_HOT_BIDS_AUCTION';
const AUCTION_LOADING = 'AUCTION_LOADING';
const UPDATE_AUCTION_ITEMS = 'UPDATE_AUCTION_ITEMS';
const SET_AUCTION_IS_NULL = 'SET_AUCTION_IS_NULL';
const UPDATE_EXPLORE_PAGE = 'UPDATE_EXPLORE_PAGE';
const SET_EXPLORE_IS_NULL = 'SET_EXPLORE_IS_NULL';
const UPDATE_ACTION_PAGE = 'UPDATE_ACTION_PAGE';

const SET_CLUBRARE_DROP_ITEMS = 'SET_CLUBRARE_DROP_ITEMS';
const UPDATE_CLUBRARE_DROP_ITEMS = 'UPDATE_CLUBRARE_DROP_ITEMS';
const UPDATE_CLUBRARE_DROP_PAGE = 'UPDATE_CLUBRARE_DROP_PAGE';
const SET_CLUBRARE_DROP_IS_NULL = 'SET_CLUBRARE_DROP_IS_NULL';

const SET_CLUBRARE_RECENT_DROP_ITEMS = 'SET_CLUBRARE_RECENT__DROP_ITEMS';
const UPDATE_CLUBRARE_RECENT__DROP_ITEMS = 'UPDATE_CLUBRARE_RECENT__DROP_ITEMS';
const UPDATE_CLUBRARE_RECENT__DROP_PAGE = 'UPDATE_CLUBRARE_RECENT__DROP_PAGE';
const SET_CLUBRARE_RECENT__DROP_IS_NULL = 'SET_CLUBRARE_RECENT__DROP_IS_NULL';
const SET_CLUBRARE_RECENT__LIST_LOADING = 'SET_CLUBRARE_RECENT__LIST_LOADING';

const SET_LAZY_LEO_ITEMS = 'SET_LAZY_LEO_ITEMS';
const UPDATE_LAZY_LEO_ITEMS = 'UPDATE_LAZY_LEO_ITEMS';
const UPDATE_LAZY_LEO_PAGE = 'UPDATE_LAZY_LEO_PAGE';
const SET_LAZY_LEO_IS_NULL = 'SET_LAZY_LEO_IS_NULL';

const MOST_LIKED_ITEMS = 'MOST_LIKED_ITEMS';
const SEARCH_KEYWORD = 'SEARCH_KEYWORD';
const EXPLORE_LIST_LOADING = 'EXPLORE_LIST_LOADING';

export {
  SET_EXPLORE_ITEMS,
  UPDATE_EXPLORE_ITEMS,
  UPDATE_ACTION_PAGE,
  SET_AUCTION,
  SET_RECENT_AUCTION,
  SET_LIVE_AUCTION,
  SET_MOST_VIEWED_AUCTION,
  SET_HOT_BIDS_AUCTION,
  SET_AUCTION_IS_NULL,
  UPDATE_EXPLORE_PAGE,
  SET_EXPLORE_IS_NULL,
  UPDATE_AUCTION_ITEMS,
  SET_CLUBRARE_DROP_ITEMS,
  UPDATE_CLUBRARE_DROP_ITEMS,
  UPDATE_CLUBRARE_DROP_PAGE,
  SET_CLUBRARE_DROP_IS_NULL,
  MOST_LIKED_ITEMS,
  AUCTION_LOADING,
  SEARCH_KEYWORD,
  EXPLORE_LIST_LOADING,
  SET_LAZY_LEO_ITEMS,
  UPDATE_LAZY_LEO_PAGE,
  UPDATE_LAZY_LEO_ITEMS,
  SET_LAZY_LEO_IS_NULL,
  SET_CLUBRARE_RECENT_DROP_ITEMS,
  UPDATE_CLUBRARE_RECENT__DROP_ITEMS,
  UPDATE_CLUBRARE_RECENT__DROP_PAGE,
  SET_CLUBRARE_RECENT__DROP_IS_NULL,
  SET_CLUBRARE_RECENT__LIST_LOADING,
};
