export const GET_ON_FAVIOURATE = 'GET_ON_FAVIOURATE';
export const UPDATE_ON_FAVIOURATE = 'UPDATE_ON_FAVIOURATE';
export const FAVIOURATE_ITEM_IS_NULL = 'FAVIOURATE_ITEM_IS_NULL';
export const UPDATE_ON_FAVIOURATE_PAGE = 'UPDATE_ON_FAVIOURATE_PAGE';
