export const SET_CREATED_ITEMS = 'SET_CREATED_ITEMS';
export const UPDATE_CREATED_ITEMS = 'UPDATED_CREATED_ITEMS';
export const SET_COLLECTIBLE_ITEMS = 'SET_COLLECTIBLE_ITEMS';
export const SET_HIDDEN_ITEMS = 'SET_HIDDEN_ITEMS';
export const UPDATE_HIDDEN_ITEMS = 'UPDATE_HIDDEN_ITEMS';
export const SET_HIDDEN_ITEM_IS_NULL = 'SET_HIDDEN_ITEM_IS_NULL';
export const UPDATE_HIDDEN_PAGE = 'UPDATE_HIDDEN_PAGE';
export const UPDATE_COLLECTIBLE_ITEMS = 'UPDATED_COLLECTIBLE_ITEMS';
export const SET_PENDING_COLLECTIBLES_ITEMS = 'SET_PENDING_COLLECTIBLES_ITEMS';
export const UPDATE_PENDING_COLLECTIBLES_ITEMS =
  'UPDATED_PENDING_COLLECTIBLES_ITEMS';
export const GET_ON_SALE = 'GET_ON_SALE';
export const UPDATE_ON_SALE = 'UPDATE_ON_SALE';
export const SET_CREATED_ITEM_IS_NULL = 'SET_CREATED_ITEM_IS_NULL';
export const UPDATE_CREATED_PAGE = 'UPDATE_CREATED_PAGE';
export const UPDATE_COLLECTED_PAGE = 'UPDATE_COLLECTED_PAGE';
export const SET_ON_SALE_ITEM_IS_NULL = 'SET_ON_SALE_ITEM_IS_NULL';
export const UPDATE_ON_SALE_PAGE = 'UPDATE_ON_SALE_PAGE';
export const SET_COLLECTED_ITEM_IS_NULL = 'SET_COLLECTED_ITEM_IS_NULL';
export const SET_PENDING_COLLECTED_ITEM_IS_NULL =
  'SET_PENDING_COLLECTED_ITEM_IS_NULL';
export const SET_COLLECTION_ITEMS = 'SET_COLLECTION_ITEMS';
export const UPDATE_COLLECTION_ITEMS = 'UPDATE_COLLECTION_ITEMS';
export const SET_COLLECTION_ITEM_IS_NULL = 'SET_COLLECTION_ITEM_IS_NULL';
export const UPDATE_COLLECTIBLE_PAGE = 'UPDATE_COLLECTIBLE_PAGE';
export const UPDATE_PENDING_COLLECTIBLE_PAGE =
  'UPDATE_PENDING_COLLECTIBLE_PAGE';
