export const SET_UNREAD_NOTIFICATION = 'SET_UNREAD_NOTIFICATION';
export const SET_UNREAD_NOTIFICATION_COUNT = 'SET_UNREAD_NOTIFICATION_COUNT';
export const SET_GET_ALL_NOTIFICATION = 'SET_GET_ALL_NOTIFICTION';
export const GET_CONVERSION_DATA = 'GET_CONVERSION_DATA';
