const SET_TOP_COLLECTION_ITEMS = 'SET_TOP_COLLECTION_ITEMS';
const SET_TOP_COLLECTION_IS_NULL = 'SET_TOP_COLLECTION_IS_NULL';
const UPDATE_TOP_COLLECTION_ITEMS = 'UPDATE_TOP_COLLECTION_ITEMS';
const TOP_COLLECTION_LIST_LOADING = 'TOP_COLLECTION_LIST_LOADING';
const UPDATE_TOP_COLLECTION_PAGE = 'UPDATE_TOP_COLLECTION_PAGE';
const COLLECTION_SEARCH_KEYWORD = 'COLLECTION_SEARCH_KEYWORD';

export {
  SET_TOP_COLLECTION_ITEMS,
  SET_TOP_COLLECTION_IS_NULL,
  UPDATE_TOP_COLLECTION_ITEMS,
  TOP_COLLECTION_LIST_LOADING,
  UPDATE_TOP_COLLECTION_PAGE,
  COLLECTION_SEARCH_KEYWORD,
};
